# Generated by Django 3.1.1 on 2020-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('time', models.TextField(blank=True)),
                ('pastbook', models.TextField(blank=True)),
                ('near', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passcode', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
