# Generated by Django 3.1.1 on 2020-09-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0002_auto_20200914_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dob',
        ),
    ]
