# Generated by Django 3.1.1 on 2020-09-14 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0003_remove_users_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
